// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cinnzojdbpmbckmotpdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpbm56b2pkYnBtYmNrbW90cGRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNjYyMzAsImV4cCI6MjA2MjY0MjIzMH0.eCvuwkN2ARsk6O7-RLO5QXJzNKuKvLUCeYqGR71k8ig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);